# ==========================================
# CIFAR-10 Onboarding Baseline Configuration
# ==========================================
# Literally Hyperparameter 


# [학습 관련 설정]
lr: 0.005             # Learning Rate (학습률)(기준 : 0.005)
momentum: 0.9         # SGD Optimizer Momentum(기준 : 0.9)
weight_decay: 0.0     # L2 Regularization (가중치 감쇠)(기준 : 0.0)
epochs: 30            # 전체 학습 에폭 수(기준 : 30)
dropout : 0.0         # (기준 : 0.0)
scheduler : "none"    # 스케줄러 : 학습이 진행됨에 따라 학습률(Learning Rate, LR)을 자동으로 조정(기준 : none)
augmentation : "none" # 데이터 증강(기준 : none)


# [모델 및 데이터 관련 설정]
width: 32            # SmallCNN 모델 채널 폭 (Width) (기준 : 32)
batch_size: 128      # 배치 크기 (기준 : 128)
seed: 42             # 재현성을 위한 난수 시드 고정 (기준 : 42)
train_num : 45000    # train data 수 (기준 : 45000)
val_num : 5000       # validation data 수 (기준 : 5000)
